---
name: "idx"
fs:
  # url: "/tmp/es"
  # 更新时间
  update_rate: "1m"
  indexed_chars: 100%
  lang_detect: true
  continue_on_error: true
  ocr:
    # language: "eng"
    enabled: false
    # pdf_strategy: "ocr_and_text"
elasticsearch:
  nodes:
    - url: "https://elasticsearch:9200"
  username: "elastic"
  password: "zhangyu"
  ssl_verification: false
rest :
  url: "http://fscrawler:8080"